language: java
jdk:
 - oraclejdk7
before_install:
 - pip install --user codecov
after_success:
 - codecov
 - echo "<settings><servers><server><id>ossrh</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>" > ~/settings.xml
 - mvn deploy -DskipITs --settings ~/settings.xml
